baseURL: https://example.com
languageCode: en-us
title: Qianyi Sun
theme: colordrop

author:
  name: Rose Qianyi Sun
  job: Developer
  image: profile.png
  github: github
  twitter: twitter
  linkedin: linkedin

taxonomies:
  tag: tags

menu:
  main:
    - identifier: blog
      name: Blog
      url: blog/
      weight: 1
    - identifier: research
      name: Research
      url: research/
      weight: 2
    - identifier: about
      name: About
      url: about
      weight: 3
    - identifier: tags
      name: Tags
      url: tags/
      weight: 4
  footer:
    - identifier: github
      name: github
      url: "#"
      weight: 1
    - identifier: twitter
      name: twitter
      url: "#"
      weight: 2
    - identifier: linkedin
      name: linkedin
      url: "#"
      weight: 3
    - identifier: keybase
      name: keybase
      url: "#"
      weight: 4
    - identifier: rss
      name: rss
      weight: 5
    - identifier: curriculum
      name: curriculum
      url: curriculum/
      weight: 6
    - identifier: email
      name: email
      url: "#"
      weight: 7

params:
  description: Hi, I'm Rose Qianyi. A passionate student/researcher in Music Technology. Learn about my research, projects, and other interests here.
  quote: Everything we do is music.  -- John Cage
  siteLogo: profile.png
  themeColor: "#000000"
  themeInverseColor: "#ffffff"

  license:
    name: Attribuition-ShareAlike
    type: by-sa
    version: "4.0"
    locale: en
    size: 88x31

languages:
  en:
    languageName: English
    weight: 1
    params:
      license:
        name: Atribuição-CompartilhaIgual
        type: by-sa
        version: "4.0"
        locale: pt_BR
        size: 88x31
